//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18051
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prism.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prism.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alarms.
        /// </summary>
        public static string APP_EXPLOREROOTVIEW_TITLE_ALARMS {
            get {
                return ResourceManager.GetString("APP_EXPLOREROOTVIEW_TITLE_ALARMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на State.
        /// </summary>
        public static string APP_EXPLOREROOTVIEW_TITLE_OPERATION_STATE {
            get {
                return ResourceManager.GetString("APP_EXPLOREROOTVIEW_TITLE_OPERATION_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string APP_MAINWINDOW_TITLE_ABOUT {
            get {
                return ResourceManager.GetString("APP_MAINWINDOW_TITLE_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Explore.
        /// </summary>
        public static string APP_MAINWINDOW_TITLE_EXPLORE {
            get {
                return ResourceManager.GetString("APP_MAINWINDOW_TITLE_EXPLORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Journal.
        /// </summary>
        public static string APP_MAINWINDOW_TITLE_JOURNAL {
            get {
                return ResourceManager.GetString("APP_MAINWINDOW_TITLE_JOURNAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Operation.
        /// </summary>
        public static string APP_MAINWINDOW_TITLE_OPERATION {
            get {
                return ResourceManager.GetString("APP_MAINWINDOW_TITLE_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Initializing....
        /// </summary>
        public static string CORE_STARTUP_MESSAGE_0 {
            get {
                return ResourceManager.GetString("CORE_STARTUP_MESSAGE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading assembly settings....
        /// </summary>
        public static string CORE_STARTUP_MESSAGE_1 {
            get {
                return ResourceManager.GetString("CORE_STARTUP_MESSAGE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading &quot;{0}&quot; unit....
        /// </summary>
        public static string CORE_STARTUP_MESSAGE_2 {
            get {
                return ResourceManager.GetString("CORE_STARTUP_MESSAGE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End initializing....
        /// </summary>
        public static string CORE_STARTUP_MESSAGE_3 {
            get {
                return ResourceManager.GetString("CORE_STARTUP_MESSAGE_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Overview.
        /// </summary>
        public static string ENUM_PRESENTATIONCONTROLCATEGORY_0 {
            get {
                return ResourceManager.GetString("ENUM_PRESENTATIONCONTROLCATEGORY_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lead inputs.
        /// </summary>
        public static string ENUM_PRESENTATIONCONTROLCATEGORY_1 {
            get {
                return ResourceManager.GetString("ENUM_PRESENTATIONCONTROLCATEGORY_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recttifiers.
        /// </summary>
        public static string ENUM_PRESENTATIONCONTROLCATEGORY_2 {
            get {
                return ResourceManager.GetString("ENUM_PRESENTATIONCONTROLCATEGORY_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Linear switches.
        /// </summary>
        public static string ENUM_PRESENTATIONCONTROLCATEGORY_3 {
            get {
                return ResourceManager.GetString("ENUM_PRESENTATIONCONTROLCATEGORY_3", resourceCulture);
            }
        }
    }
}
